---
title: "Reporte de la Situación Problema"
author: "Equipo 4"
date: today
format:
  docx:
    toc: true          # Include table of contents
    toc-depth: 3       # Levels in TOC
---

# Etapa 1. Conociendo el negocio

Para esta primera etapa, empezaremos por cargar las librerías que necesitamos y establecemos algunas opciones de configuración:

```{r}
#| output: false
library(tidyverse)
library(here)
library(readxl)
library(maps)

options(scipen = 999)
```
Ahora cargamos los datos que nos proporcionó el Socio Formador:
```{r}
calidad_aire_2020_tbl <- read_excel(here("data", "BD 2020.xlsx")) 
calidad_aire_2021_tbl <- read_excel(here("data", "BD 2021.xlsx")) 
calidad_aire_2022_tbl <- read_excel(here("data", "BD 2022.xlsx")) 
calidad_aire_2023_tbl <- read_excel(here("data", "BD 2023.xlsx")) 
calidad_aire_2024_tbl <- read_excel(here("data", "BD 2024.xlsx")) 
calidad_aire_2025_tbl <- read_excel(here("data", "BD 2025.xlsx")) 

glimpse(calidad_aire_2020_tbl)
glimpse(calidad_aire_2021_tbl)
glimpse(calidad_aire_2022_tbl)
glimpse(calidad_aire_2023_tbl)
glimpse(calidad_aire_2024_tbl)
glimpse(calidad_aire_2025_tbl)

bases <- list(
  "2020" = calidad_aire_2020_tbl,
  "2021" = calidad_aire_2021_tbl,
  "2022" = calidad_aire_2022_tbl,
  "2023" = calidad_aire_2023_tbl,
  "2024" = calidad_aire_2024_tbl,
  "2025" = calidad_aire_2025_tbl
)

dimensiones <- purrr::imap_dfr(bases, ~ tibble(
  Año = .y,
  Registros = nrow(.x),
  Columnas = ncol(.x)
))

dimensiones

variables_por_año <- purrr::imap_dfr(bases, ~ tibble(
  Año = .y,
  Variable = names(.x)
))

variables_por_año

yjfg

```




